# spring
spring:
  application:
    name: ljdate-user
  datasource:
    # local
    url: jdbc:mysql://120.79.74.63:3307/datedb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

server:
  port: 8081


# dubbo
dubbo:
  application:
    name: ljdate-user
  protocol:
    name: dubbo
    port: 20880
  registry:
    # docker
    address: zookeeper://120.79.74.63:2182 #localhost 2181
  provider:
    timeout: 3000

# version
demo:
  api:
    version: 1.0.0


# mybatis
mybatis:
  type-aliases-package: com.whu.common.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000

# pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# fastdfs
img:
  server:
    url:
      http://120.79.74.63:8080/