redis:
  host: 120.79.74.63 #localhost
  port: 6380 #6383
  timeout: 10
  password: 123456
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500
spring:
  rabbitmq:
    host: 120.79.74.63 #localhost
    port: 5673
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5
      concurrency: 10
      max-concurrency: 20
      prefetch: 5